### ISSUE TITLE
Package declares itself incompatible with Node 10

### ISSUE THREAD

**Issue by benvoynick** [75lb/stream-read-all#2]
Judging by commit comments it looks like this package is still supposed to support Node 10. However, package.json specifies a node engine ">10" (rather than ">=10") and so Node 10.x regards version 3 as incompatible.

**Comment by 75lb** [comment]
oops, i'll fix that now..

**Comment by 75lb** [comment]
Fixed and released in v3.0.1 - let me know if you find anything else..
